server:
  port: 8080

spring:
  application.name: workshop-web-products
  flyway:
    enabled: true
    locations: classpath:migration/versions,classpath:migration/develop

  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

# Actuator endpoints configuration
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: [ info, health, metrics, prometheus ]
